Import('*')

# SimObject('random_number_gen.py',
#           sim_objects=['random_number_gen'])
# Source('random_number_gen.cc')

Source('venus_instr_pkt.cc')
SimObject('VenusPacketGen.py',
          sim_objects=['VenusPacketGen'])
Source('VenusPacketGen.cc')
SimObject('VenusSequencer.py',
          sim_objects=['VenusSequencer'])
Source('VenusSequencer.cc')
# DebugFlag('random_number_genDebug')